@echo off
REM Batch file to set credentials and run continuous alerts script

echo Setting Upstox API credentials...
set UPSTOX_API_KEY=e3d3c1d1-5338-4efa-b77f-c83ea604ea43
set UPSTOX_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIzUUFSVEoiLCJqdGkiOiI2OTE0MDE1MDY0ZmYzYTViMWM4YTk4NTQiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc2MjkxODczNiwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzYyOTg0ODAwfQ.ETjfi9F3QQqCqCtiwypBSsMF_zb_zqfUfifv3t6q7sI

echo.
echo ✅ Credentials set
echo.
echo Starting continuous alerts script...
echo.

python scripts/run_continuous_alerts.py

pause

